'use client';

import { useEffect, useMemo, useState } from 'react';
import { rupiah } from '@/lib/format';

type Item = { id:string; type:'INCOME'|'EXPENSE'; category:string; description:string; amount:number; cashierName:string; createdAt:string };

export default function BukuKasPage() {
  const [items,setItems]=useState<Item[]>([]); const [type,setType]=useState<'INCOME'|'EXPENSE'>('INCOME');
  const [amount,setAmount]=useState(''); const [category,setCategory]=useState(''); const [description,setDescription]=useState(''); const [q,setQ]=useState(''); const [msg,setMsg]=useState('');
  async function load(){ const res=await fetch(`/api/cashbook?q=${encodeURIComponent(q)}`); setItems(await res.json()); }
  useEffect(()=>{load();},[]);
  const summary=useMemo(()=>{const income=items.filter(i=>i.type==='INCOME').reduce((a,b)=>a+b.amount,0); const expense=items.filter(i=>i.type==='EXPENSE').reduce((a,b)=>a+b.amount,0); return {income,expense,balance:income-expense};},[items]);
  async function submit(){ setMsg(''); const res=await fetch('/api/cashbook',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,amount:Number(amount),category,description,cashierName:'Admin'})}); const data=await res.json(); if(!res.ok){setMsg(data.message||'Gagal menyimpan');return;} setAmount('');setCategory('');setDescription('');setMsg('Berhasil disimpan ke Buku Kas'); load(); }
  const categories=type==='INCOME'?['Penjualan','Modal Tambahan','Piutang Dibayar','Lainnya']:['Belanja Stok','Bayar Listrik','Bayar Air','Gaji Karyawan','Transportasi','Operasional','Lainnya'];
  return <main className="mx-auto max-w-6xl px-4 py-8"><div className="grid gap-4 md:grid-cols-3"><div className="card p-5"><p className="font-bold text-slate-500">Uang Masuk</p><p className="text-2xl font-black text-green-700">{rupiah(summary.income)}</p></div><div className="card p-5"><p className="font-bold text-slate-500">Uang Keluar</p><p className="text-2xl font-black text-red-700">{rupiah(summary.expense)}</p></div><div className="card p-5"><p className="font-bold text-slate-500">Saldo</p><p className="text-2xl font-black text-green-950">{rupiah(summary.balance)}</p></div></div><section className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="card p-6"><h1 className="text-2xl font-black text-green-950">Tambah Buku Kas</h1><div className="mt-5 space-y-4"><select className="input" value={type} onChange={e=>{setType(e.target.value as 'INCOME'|'EXPENSE');setCategory('');}}><option value="INCOME">Uang Masuk</option><option value="EXPENSE">Uang Keluar</option></select><select className="input" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Pilih Kategori</option>{categories.map(c=><option key={c}>{c}</option>)}</select><input className="input" type="number" placeholder="Nominal" value={amount} onChange={e=>setAmount(e.target.value)} /><textarea className="input min-h-28" placeholder="Keterangan" value={description} onChange={e=>setDescription(e.target.value)} /><button className="btn btn-primary w-full" onClick={submit}>Simpan</button>{msg&&<p className="font-bold text-green-800">{msg}</p>}</div></div><div className="card overflow-hidden p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-2xl font-black text-green-950">Riwayat Buku Kas</h2><div className="flex gap-2"><input className="input" placeholder="Cari keterangan" value={q} onChange={e=>setQ(e.target.value)} /><button className="btn btn-light" onClick={load}>Cari</button></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Tanggal</th><th className="p-3">Jenis</th><th className="p-3">Kategori</th><th className="p-3">Keterangan</th><th className="p-3">Nominal</th><th className="p-3">User</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-b"><td className="p-3">{new Date(i.createdAt).toLocaleString('id-ID')}</td><td className="p-3"><span className={i.type==='INCOME'?'badge-income':'badge-expense'}>{i.type==='INCOME'?'Uang Masuk':'Uang Keluar'}</span></td><td className="p-3">{i.category}</td><td className="p-3">{i.description}</td><td className="p-3 font-bold">{rupiah(i.amount)}</td><td className="p-3">{i.cashierName}</td></tr>)}</tbody></table></div></div></section></main>;
}
